mysql.url = "jdbc:mysql://localhost:3306/shubham_jdbc";
mysql.user = "root";
mysql.pass = "9657";




package com.shubh;

import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Properties;

public class Crud {

	public static void main(String[] args) {
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			
			
			
			//create .properties file
			//create fileIOStream 
			//Create properties Obj
			//load the .properties file
			//get using properties method
			
		
				
				
				FileInputStream f1 = new FileInputStream("C:\\Users\\desai\\OneDrive\\Documents\\MDM\\JDBC\\Codes of JDBC\\Detailed.properties");
				
				Properties p1 = new Properties();
				p1.load(f1);
				
				String url = (String) p1.getProperty("mysql.url");
				String user = (String) p1.get("mysql.user");
				String pass = (String) p1.get("mysql.pass");
				
				
				Connection connection = DriverManager.getConnection(url, user, pass);
				
				System.out.println(connection+" "+connection.getCatalog());
			
			
		
		} catch (Exception e) {
			
			e.printStackTrace();
		}
		
		
		
		

	}

}
